---
title: "Analysis of rare gastroenterological diseases"
description: |
 A case study of microscopic analysis using our multiple networks framework
author:
  - name: Pisanu Ize Buphamalai
    affiliation: CeMM
    affiliation_url: www.cemm.at 
date: "`r Sys.Date()`"
output: distill::distill_article
---

This is an example to show the microscopic level of the discovery.
```{r}
source("../functions/readdata_functions.R")
source("../functions/readdata_functions.R")
source("../functions/process_LCC_result.R")

library(igraph)

g = process_graph_data("../data/network_edgelists/")

rare_genetic_result_folder = "../cache/output/Orphageneset_rare/"

# load  network labels
network_info = read_tsv("../data/network_details.tsv")


## process the results LCC significance
result_df = readRDS(paste0(rare_genetic_result_folder, "LCC_and_distance_calculation_results.RDS"))
  
processed_result_df = process_LCC_result(result_df)

rare_genetic_diseases_genes <- process_disease_genes_data("../data/table_disease_gene_assoc_orphanet_genetic.tsv", 20,2000)

individual_diseases_genes <- read_tsv("../data/orphaNet_disease_gene_association_with_roots.tsv")
```

# Rare genetic gastro- diseases

```{r}
disease_of_interest <- "Rare genetic gastroenterological disease"   

# unique disease set under the term
individual_gene_set <- individual_diseases_genes %>% dplyr::filter(grepl(disease_of_interest, roots))

# all genes associated
genes_set <- rare_genetic_diseases_genes$disgene_list[[disease_of_interest]]

# print the paged table
individual_gene_set %>% select(label, genes, n_genes) %>% rmarkdown::paged_table()
```

`r disease of interest` has `r nrow(individual_gene_set)` disease terms and `length(genes_set)` associated genes.


```{r treemap}
# load package for producing treemap
pacman::p_load(treemap)

# set a threshold for minimal amount of genes required to include in the plotting
threshold = 2

individual_gene_set_wrap <- individual_gene_set %>% dplyr::filter(n_genes >= threshold) %>% select(label, n_genes)

n_removed <- sum(individual_gene_set$n_genes<=threshold)
#individual_gene_set_wrap <- rbind(individual_gene_set_wrap, data.frame(label = sprintf("Other (%i diseases with one or two associated genes)", n_removed), n_genes = n_removed))


# Create data
{group <- ifelse(individual_gene_set_wrap$n_genes > threshold+2, 
                individual_gene_set_wrap$label, str_trunc(individual_gene_set_wrap$label, 50, side = "right"))

value <- individual_gene_set_wrap$n_genes
data <- data.frame(group,value)
 

treemap(data,
        palette = "Set3",   
        title = disease_of_interest,
            index="group",
            vSize="value",
            type="index"
            )


# treemap - uncomment to plot
#pdf("../Figs/treemap_gastroenterological.pdf", width = 5, height = 4)
```

# 
```{r}
signif_nets <- processed_result_df %>% dplyr::filter(name == disease_of_interest, LCC.signif != "none") %>% arrange(desc(LCC.zscore)) %>% pull(network)

# degrees each gene in each network
degree_diseasegenes <- sapply(g[signif_nets], function(x) degree(x, v = intersect(V(x)$name, genes_set)))

library(ggraph)
library(tidygraph)

disease_graph <- lapply(signif_nets, function(x) g[[x]]- setdiff(V(g[[x]])$name, genes_set))
names(disease_graph) <- signif_nets

disease_graph_df <- lapply(disease_graph, as_data_frame) %>% bind_rows(., .id = "network") %>% mutate(network = factor(network, levels = signif_nets))


disease_tidygraph <- as_tbl_graph(disease_graph_df) %>% 
    mutate(degree = centrality_degree(mode = 'all'))

tidygraph_ggrpah <- ggraph(disease_tidygraph, layout = 'kk')

p <- tidygraph_ggrpah + 
  geom_edge_density(aes(fill = network),
                    show.legend = FALSE) + 
  geom_edge_fan(aes(alpha = stat(index), 
                    col = network), 
                  show.legend = FALSE) + 
  geom_node_point(col = "white",
                  alpha = 0.25,
                   show.legend  = F, 
                   size = 1) + 
  facet_edges(~factor(network, levels = signif_nets)) + 
  # black theme
    theme_graph(fg_text_colour = 'white', 
              background = "black",
              text_colour = "white") 
 
# uncomment when need to replot and save
#ggsave2(sprintf("../Figs/networks_%s.pdf", disease_of_interest), plot = p, width = 10, height = 6)
#ggsave2(sprintf("../Figs/networks_%s_separate_dimmed.png", disease_of_interest), plot = p, width = 10, height = 6) 


p


```

```{r network plot - white background}

p <- tidygraph_ggrpah + 
  geom_edge_density(aes(fill = network),
                    show.legend = FALSE) + 
  geom_edge_fan(aes(alpha = stat(index), 
                    col = network), 
                  show.legend = FALSE) + 
  geom_node_point(col = "grey50",
                  alpha = 0.25,
                   show.legend  = F, 
                   size = 0.75) + 
  facet_edges(~factor(network, levels = signif_nets)) + 
  theme_graph(fg_text_colour = 'black', 
              background = "white",
              text_colour = "black") 

p

ggsave2(sprintf("../Figs/networks_%s_separate_white_bg.png", disease_of_interest), plot = p, width = 10, height = 6) 
```


# Prioritise networks with smallest LCC

```{r}
disease_graph_df_collapse <- disease_graph_df %>% 
  group_by(from, to) %>% summarise(networks = list(network)) %>% 
  rowwise() %>% 
  mutate(n_network = length(networks), 
         displaytype = signif_nets[min(which(signif_nets %in% networks))])

# graph to be displayed
graph_disp <- disease_graph_df_collapse %>% as_tbl_graph() %>% 
    mutate(degree = centrality_degree(mode = 'all'))


graph_disp_ggraph <- ggraph(graph_disp, layout = 'kk')

## coloring edges
p <- graph_disp_ggraph +
    geom_edge_fan(aes(alpha = stat(index), col = displaytype),
                  show.legend = F) +
    geom_node_point(aes(size = degree), col = "white", 
                    show.legend  = F) + 
    theme_graph(foreground = 'black', fg_text_colour = 'white', background = "black",
                text_colour = "white") +
   scale_edge_color_brewer(type = "div", palette = "Spectral") 

# uncomment when need to replot and save
#ggsave2(sprintf("../Figs/network_combined_%s.pdf", disease_of_interest), p, width = 9, height = 6)

p
```



```{r}
p <- graph_disp_ggraph +
    geom_edge_fan(aes(alpha = stat(index), col = displaytype)) +
    geom_node_point(aes(size = degree), col = "white", 
                    show.legend  = F) + 
  geom_edge_density(aes(fill = displaytype)) + 
    theme_graph(foreground = 'black', fg_text_colour = 'white', background = "black",
                text_colour = "white") +
   # scale_color_brewer(type = "seq", palette = "Blues", direction = -1) +
   scale_edge_color_brewer(type = "div", palette = "Spectral") 

p
```


# highlight by the disease
```{r}
# assign a disease label to each gene
# a dictionary linking gene to representative disease names
individual_gene_list <- individual_gene_set %>%
arrange(desc(n_genes)) %>%
mutate(genes = str_split(genes, ";"),
new_label = ifelse(n_genes > 4, label, "Other")) %>%
select(genes, new_label) %>%
unnest(genes) %>%
distinct(genes, .keep_all = T) %>%
deframe()

p <- graph_disp_ggraph +
    geom_edge_fan(aes(alpha = stat(index),col = "white"), show.legend = F) +
    geom_node_point(aes(size = degree,
                        col = individual_gene_list[name]),# col = "white", 
                    show.legend  = T) + 
    theme_graph(foreground = 'black', fg_text_colour = 'white', background = "black",
                text_colour = "white") +
    scale_color_brewer(type = "seq", palette = "PuBu", direction = -1) +
  scale_edge_color_manual(values = "#ffffb2")


# uncomment this when need to resave the plot
#ggsave2(sprintf("../Figs/network_combined_%s_node_labels.pdf", disease_of_interest), p, width = 12, height = 6)

p
```


## add node labels and apply community detection

```{r}

graph_community <- disease_graph_df_collapse %>% 
  dplyr::filter("coex_EMC" %in% networks) %>%
  as_tbl_graph(directed = F) %>% 
  activate(nodes) %>%
    mutate(degree = centrality_degree(mode = 'all'),
      community = as.factor(group_louvain()))

graph_community_gg <- ggraph(graph_community,layout = 'kk')

p <- graph_community_gg +
    geom_edge_fan(aes(col = "white")) +
    geom_node_point(aes(size = degree, col = community),
                    show.legend  = T) + 
    theme_graph(foreground = 'black', fg_text_colour = 'white', background = "black",
                text_colour = "white") +
   # scale_color_brewer(type = "seq", palette = "Blues", direction = -1) +
  scale_edge_color_manual(values = "white") 

p
```


```{r}
graph_community_gg$data %>% arrange(community) %>% select(name, community) %>% dplyr::filter(community %in% c(1:5)) %>% pull(name) %>% paste(., collapse = ", ")
```

```{r}
graph_community_gg$data %>% arrange(community) %>% select(name, community) %>% dplyr::filter(community %in% c(1:5)) %>% View()
```

