---
title: "Leave-one-out cross validation results"
description: |
  LOOCV results analysis for all Orphanet disease groups: this is to simulate the actual rare disease gene discovery
author:
  - name: Pisanu Ize Buphamalai
    affiliation: CeMM
    affiliation_url: www.cemm.at 
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)

pacman::p_load("cvAUC")
library(patchwork)
## function to compute AUC from rank



create_label <- function(pos, max){
  label <- rep(-1,max)
  label[pos] <- 1
  return(label)
}

auc_output<-function(rank_df){
  #' @input rank_df: a two column data frame, with label and prediction respectively
  max = rank_df$max[1]
  
  rank_label <- lapply(rank_df[,1], function(x) create_label(x, max))
 
  rank_prediction <- lapply(1:nrow(rank_df), function(x) rev(1:max))

  out <- cvAUC(rank_prediction, rank_label)
  return(out)
}



## load the data

# result from using significant networks
rank_df_all_folds <- readRDS("../cache/LCC_LOOCV_ranking_rare_genetic_diseases.RDS")
rank_df_all_folds <- lapply(rank_df_all_folds, function(df) df[, c("RankArithmP", "max")])

# result from using PPI alone
rank_df_all_folds_only_PPI <- readRDS("../cache/LCC_LOOCV_ranking_rare_genetic_diseases_only_PPI.RDS")
# Since using one network there is one ranking column
rank_df_all_folds_only_PPI <- lapply(rank_df_all_folds_only_PPI, function(df) df[, c("rank", "max")])

# results from all networks
rank_df_all_folds_allnets <-readRDS("../cache/LCC_LOOCV_ranking_rare_genetic_diseases_allnets.RDS")
rank_df_all_folds_allnets_used <- lapply(rank_df_all_folds_allnets, function(df) df[, c("RankArithmP", "max")])
```


# How many times a left-out gene got picked up within top 10, top 100

```{r}
#top10

top10prop <- sapply(rank_df_all_folds, function(df) sum(df[,1]<=10)/nrow(df))
top100prop <- sapply(rank_df_all_folds, function(df) sum(df[,1]<=100)/nrow(df))

top10prop_ppi <- sapply(rank_df_all_folds_only_PPI, function(df) sum(df[,1]<=10)/nrow(df))
top100prop_ppi <- sapply(rank_df_all_folds_only_PPI, function(df) sum(df[,1]<=100)/nrow(df))

top10prop_allnet <- sapply(rank_df_all_folds_allnets_used, function(df) sum(df[,1]<=10)/nrow(df))
top100prop_allnet <- sapply(rank_df_all_folds_allnets_used, function(df) sum(df[,1]<=100)/nrow(df))

top100prop_df <- tibble(signif = top100prop, ppi = top100prop_ppi, allnets = top100prop_allnet)
top100prop_df$name <- names(top100prop)

top100prop_df <- top100prop_df %>% pivot_longer(!name, names_to =  "network_group", values_to = "percent")

ggplot(top100prop_df) + geom_violin(aes(x = network_group, y = percent, fill = network_group))

pacman::p_load("ggstatsplot")


ggwithinstats(data = top100prop_df %>% mutate(network_group = factor(network_group, levels = c("ppi", "allnets","signif"))),
                      x = network_group,
                      y = percent,
                      type = "np")
```


```{r}

ranks <- list(signif = rank_df_all_folds,ppi =  rank_df_all_folds_only_PPI, allnets = rank_df_all_folds_allnets_used)

# compute AUC values based on rank:
   # for LOOCV, AUC is simply ratio between rank to max (col2-col1) and range (col2-1)
auc_compute <- function(x){(x[,2]-x[,1])/(x[,2]-1)}
aucvals <- lapply(ranks, function(x) lapply(x, auc_compute))
 
aucvals_summary <-  lapply(aucvals, function(x) lapply(x, summary))

aucvals_summary_df <- lapply(aucvals_summary, function(df) bind_rows(df, .id = "disease"))
aucvals_summary_df <- bind_rows(aucvals_summary_df, .id = "type")
aucvals_summary_df <- as_tibble(aucvals_summary_df)  
aucvals_summary_df[,3:8] <- apply(aucvals_summary_df[,3:8],2, as.double)

ggwithinstats(data = aucvals_summary_df %>% mutate(type = factor(type, levels = c("ppi", "allnets","signif"))),
                      x = type,
                      y = Mean,
                      type = "np") + xlab("AUC")

```



## AUC plot

```{r}

network_labels = c("significant networks", "all networks", "PPI only")
palettes <- c('#66c2a5','#fc8d62','#8da0cb')

library(cowplot)





p <- ggplot(aucvals_summary_df,
            aes(x=disease, fill = type, group = type)) +
   geom_ribbon(aes(ymin = `1st Qu.`, ymax = `3rd Qu.`), alpha = 0.25) + 
  geom_line(aes(y = Median, col = type), linetype = 2) +
  coord_flip() + xlab("disease") + ylab("fold AUC") + theme_minimal_hgrid() + theme(legend.position = "bottom") +
  ggtitle("ROC-AUC comparison", subtitle = "area spans 25, 50 and 75% quantile") + 
  scale_fill_manual(values=palettes) + scale_color_manual(values=palettes)

#ggsave("../Figs/cvROC/AUC_folds_comparison.pdf", p, width = 7, height = 6)
 
p
```


```{r, eval = FALSE}
## compare all methods in one go -> printed in one paper


# 
# if(!dir.exists("../Figs/cv_LOO_ROC")){
#   dir.create("../Figs/cv_LOO_ROC")
# }
# 
# 
# # store AUCROC for each disease group in separate files
# 
# palettes <- c('#66c2a5','#fc8d62','#8da0cb')
# 
# 
# for(i in all_diseases)  #Plot fold AUCs
#   { 
#    pdf(paste0("../Figs/cv_LOO_ROC/",i,".pdf"), width = 4, height = 4)
#   par(mar = c(2,2,2,1)+0.1)
#    # signif
#     plot(aucvals_signif[[i]]$perf, col=palettes[3],  avg="vertical", main=str_remove_all(i, "Rare |genetic | disease| diseases"), xlab = "", ylab ="", font.main = 8, lwd = 3)
#     
#     # all networks
#     plot(aucvals_all[[i]]$perf, col=palettes[1], avg="vertical", add=TRUE, lwd = 2)
#     
#     # PPI alone
#     plot(aucvals_PPI[[i]]$perf, col=palettes[2], avg="vertical", add=TRUE, lwd = 2)
#     
#     dev.off()
#     }
# 

```


### AUC plot for all diseases

```{r}

# auc_to_df <- function(auc_object, label = NULL){
#   AUC_folds<-lapply(auc_object, function(x) x$fold.AUC)
# 
#   AUC_folds<-melt(AUC_folds)
#   colnames(AUC_folds)<-c("AUC", "name")
# 
#   AUC_folds<-AUC_folds %>% mutate(name=fct_reorder(name, AUC))
#   
#   if(!is.null(label)){
#     AUC_folds$label <- label
#   }
#   return(AUC_folds)
# }

```





```{r}


# shorten names by manual labels

# short_names = c(
# "Rare genetic developmental defect...", 
# "Rare genetic endocrine disease", 
# "Rare genetic neurological disorder", 
# "Rare chromosomal anomaly", 
# "Rare inborn errors of metabolism", 
# "Rare genetic eye disease", 
# "Rare genetic bone disease", 
# "Rare genetic tumor", 
# "Rare genetic immune disease", 
# "Rare genetic skin disease", 
# "Genetic otorhinolaryngologic disease", 
# "Rare genetic cardiac disease", 
# "Rare genetic renal disease", 
# "Genetic infertility", 
# "Rare genetic urogenital disease", 
# "Rare genetic gastroenterological disease", 
# "Rare genetic hepatic disease", 
# "Rare genetic gynecological diseases", 
# "Rare genetic hematologic disease", 
# "Rare genetic rheumatologic disease", 
# "Ciliopathy", 
# "Inherited cancer-predisposing syndrome", 
# "Rare genetic odontologic disease", 
# "Laminopathy", 
# "Rare genetic vascular disease", 
# "RASopathy")
# 
# p <- ggplot(AUC_folds_summary %>%
#               mutate(name_short = factor(name, levels = levels(name), labels = short_names)),
#             aes(x=name_short, fill = label, group = label)) +
#    geom_ribbon(aes(ymin = Q25, ymax = Q75), alpha = 0.25) +
#   geom_line(aes(y = med, col = label), linetype = 2) +
#   coord_flip() + xlab("disease") + ylab("fold AUC") + theme_minimal_hgrid() + theme(legend.position = "bottom") +
#   ggtitle("ROC-AUC comparison", subtitle = "area spans 25, 50 and 75% quantile") +
#   scale_fill_manual(values=palettes) + scale_color_manual(values=palettes)
# 


#ggsave("../Figs/cvROC/AUC_folds_comparison_short_names.pdf", p, width = 6, height = 6)

p
```



