---
title: "Cross validation results"
description: |
  A new article created using the Distill format.
author:
  - name: Pisanu Ize Buphamalai
    affiliation: CeMM
    affiliation_url: www.cemm.at 
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
A4height <- 29.7
A4width <- 21

pacman::p_load("cvAUC")
library(patchwork)
## function to compute AUC from rank

auc_output<-function(rank_df){
  #' @input rank_df: a two column data frame, with label and prediction respectively
  rank_label<-lapply(rank_df, function(x) x[,1])
  rank_prediction<-lapply(rank_df, function(x) -x[,2])
  
  out <- cvAUC(rank_prediction, rank_label)
  return(out)
}

## load the data

# result from using significant networks
rank_df_all_folds <- readRDS("../cache/LCC_CV_ranking_rare_genetic_diseases_no_LCC_recompute.RDS")
rank_df_all_folds <- lapply(rank_df_all_folds, function(x) lapply(x, function(df) df[, c("trueset", "RankArithmP")]))

# result from using PPI alone
rank_df_all_folds_only_PPI <- readRDS("../cache/LCC_CV_ranking_rare_genetic_diseases_only_PPI.RDS")
# Since using one network there is one ranking column
rank_df_all_folds_only_PPI <- lapply(rank_df_all_folds_only_PPI, function(x) lapply(x, function(df) df[, c("trueset", "rank")]))

# results from all networks
rank_df_all_folds_allnets <-readRDS("../cache/LCC_CV_ranking_rare_genetic_diseases_allnets.RDS")
rank_df_all_folds_allnets_used <- lapply(rank_df_all_folds_allnets, function(x) lapply(x, function(df) df[, c("trueset", "RankArithmP")]))
```


```{r}

## ROC curve -> from k-fold validation: commonly assessed and combine

## compute AUC from the rank through CVAUC - combining cross validation results

aucvals_signif <-lapply(rank_df_all_folds, auc_output)
aucvals_PPI <-lapply(rank_df_all_folds_only_PPI, auc_output)
aucvals_all <-lapply(rank_df_all_folds_allnets_used, auc_output)

all_diseases <- names(aucvals_all)

# report median values of AUC across all diseases given the different methods
print("median AUC for all disease groups: signif, PPI, and all networks")
print(median(sapply(aucvals_signif, function(x) x$cvAUC)))
print(median(sapply(aucvals_PPI, function(x) x$cvAUC)))
print(median(sapply(aucvals_all, function(x) x$cvAUC)))
```




```{r, eval=FALSE}
#plotting -----------------


# all diseases in one plot

## signif only
pdf(paste0("../Figs/cvROC/all_rare_genetic_diseases_no_LCC_remeasure.pdf"), width=12, height=10)
par(mfrow=c(5,6))
{
 for(i in all_diseases)  #Plot fold AUCs
  { plot(aucvals_signif[[i]]$perf, col="grey82", lty=3, main=paste(i))
    
    #Plot CV AUC
    plot(aucvals_signif[[i]]$perf, col="red", avg="vertical", add=TRUE)}
}
  
dev.off()


## PPI only
pdf(paste0("../Figs/cvROC/all_rare_genetic_diseases_PPI_only.pdf"), width=12, height=10)
par(mfrow=c(5,6))
{
 for(i in all_diseases)  #Plot fold AUCs
  { plot(aucvals_PPI[[i]]$perf, col="grey82", lty=3, main=paste(i))
    
    #Plot CV AUC
    plot(aucvals_PPI[[i]]$perf, col="red", avg="vertical", add=TRUE)}
}
  
dev.off()

## allnets
pdf(paste0("../Figs/cvROC/all_rare_genetic_diseases_all_networks.pdf"), width=12, height=10)
par(mfrow=c(5,6))
{
 for(i in all_diseases)  #Plot fold AUCs
  { plot(aucvals_all[[i]]$perf, col="grey82", lty=3, main=paste(i))
    
    #Plot CV AUC
    plot(aucvals_all[[i]]$perf, col="red", avg="vertical", add=TRUE)}
}
  
dev.off()
```

## AUC plot

```{r, eval = FALSE}
## compare all methods in one go -> printed in one paper

palettes <- c('#66c2a5','#fc8d62','#8da0cb')

pdf(paste0("../Figs/cvROC/all_rare_genetic_diseases_compared_all_methods.pdf"), paper = "a4")
par(mfrow=c(7,4))
{
 for(i in all_diseases)  #Plot fold AUCs
  { 
   # signif
    plot(aucvals_signif[[i]]$perf, col=palettes[1],  avg="vertical", main=str_remove_all(i, "Rare |genetic | disease"))
    
    # all networks
    plot(aucvals_all[[i]]$perf, col=palettes[2], avg="vertical", add=TRUE)
    
    # PPI alone
    plot(aucvals_PPI[[i]]$perf, col=palettes[3], avg="vertical", add=TRUE)
    
    }
}
  
dev.off()


```

```{r}
# store AUCROC for each disease group in separate files

palettes <- c('#66c2a5','#fc8d62','#8da0cb')


for(i in all_diseases)  #Plot fold AUCs
  { 
   pdf(paste0("../Figs/cvROC/by_disease/",i,".pdf"), width = 4, height = 4)
  par(mar = c(2,2,2,1)+0.1)
   # signif
    plot(aucvals_signif[[i]]$perf, col=palettes[3],  avg="vertical", main=str_remove_all(i, "Rare |genetic | disease| diseases"), xlab = "", ylab ="", font.main = 8, lwd = 3)
    
    # all networks
    plot(aucvals_all[[i]]$perf, col=palettes[1], avg="vertical", add=TRUE, lwd = 2)
    
    # PPI alone
    plot(aucvals_PPI[[i]]$perf, col=palettes[2], avg="vertical", add=TRUE, lwd = 2)
    
    dev.off()
    }


```


### AUC plot for all diseases

```{r}

auc_to_df <- function(auc_object, label = NULL){
  AUC_folds<-lapply(auc_object, function(x) x$fold.AUC)

  AUC_folds<-melt(AUC_folds)
  colnames(AUC_folds)<-c("AUC", "name")

  AUC_folds<-AUC_folds %>% mutate(name=fct_reorder(name, AUC))
  
  if(!is.null(label)){
    AUC_folds$label <- label
  }
  return(AUC_folds)
}

AUC_folds_signif <- auc_to_df(aucvals_signif)

ggplot(AUC_folds_signif, aes(x=name, y=AUC)) + geom_boxplot() + geom_jitter() + coord_flip() + xlab("disease") + ylab("fold AUC") + theme_minimal()
```


### AUC plot for all diseases and all methods

```{r}

AUC_folds_signif <- auc_to_df(aucvals_signif, label = "significant networks")
AUC_folds_allnets <- auc_to_df(aucvals_all, label = "all networks")
AUC_folds_PPI <- auc_to_df(aucvals_PPI, label = "PPI only")

AUC_folds <- bind_rows(AUC_folds_signif, AUC_folds_allnets, AUC_folds_PPI)

ggplot(AUC_folds, aes(x=name, y=AUC, fill = label)) + geom_boxplot() + coord_flip() + xlab("disease") + ylab("fold AUC") + theme_minimal() + theme(legend.position = "bottom")
```

```{r}
# compute median and 25% and 75% quantile

AUC_folds_summary <- AUC_folds %>% 
  group_by(name, label) %>% 
  summarise(mean = mean(AUC), med = median(AUC), Q25 = quantile(AUC, 0.25), Q75 = quantile(AUC, 0.75))

library(cowplot)
p <- ggplot(AUC_folds_summary,
            aes(x=name, fill = label, group = label)) +
   geom_ribbon(aes(ymin = Q25, ymax = Q75), alpha = 0.25) + 
  geom_line(aes(y = med, col = label), linetype = 2) +
  coord_flip() + xlab("disease") + ylab("fold AUC") + theme_minimal_hgrid() + theme(legend.position = "bottom") +
  ggtitle("ROC-AUC comparison", subtitle = "area spans 25, 50 and 75% quantile") + 
  scale_fill_manual(values=palettes) + scale_color_manual(values=palettes)

#ggsave("../Figs/cvROC/AUC_folds_comparison.pdf", p, width = 7, height = 6)
 
p
```


```{r}


# shorten names by manual labels

short_names = c(
"Rare genetic developmental defect...", 
"Rare genetic endocrine disease", 
"Rare genetic neurological disorder", 
"Rare chromosomal anomaly", 
"Rare inborn errors of metabolism", 
"Rare genetic eye disease", 
"Rare genetic bone disease", 
"Rare genetic tumor", 
"Rare genetic immune disease", 
"Rare genetic skin disease", 
"Genetic otorhinolaryngologic disease", 
"Rare genetic cardiac disease", 
"Rare genetic renal disease", 
"Genetic infertility", 
"Rare genetic urogenital disease", 
"Rare genetic gastroenterological disease", 
"Rare genetic hepatic disease", 
"Rare genetic gynecological diseases", 
"Rare genetic hematologic disease", 
"Rare genetic rheumatologic disease", 
"Ciliopathy", 
"Inherited cancer-predisposing syndrome", 
"Rare genetic odontologic disease", 
"Laminopathy", 
"Rare genetic vascular disease", 
"RASopathy")

p <- ggplot(AUC_folds_summary %>%
              mutate(name_short = factor(name, levels = levels(name), labels = short_names)),
            aes(x=name_short, fill = label, group = label)) +
   geom_ribbon(aes(ymin = Q25, ymax = Q75), alpha = 0.25) +
  geom_line(aes(y = med, col = label), linetype = 2) +
  coord_flip() + xlab("disease") + ylab("fold AUC") + theme_minimal_hgrid() + theme(legend.position = "bottom") +
  ggtitle("ROC-AUC comparison", subtitle = "area spans 25, 50 and 75% quantile") +
  scale_fill_manual(values=palettes) + scale_color_manual(values=palettes)



ggsave("../Figs/cvROC/AUC_folds_comparison_short_names.pdf", p, width = 6, height = 6)

p
```


# p-value based on statistical test for avg ROC curve

```{r}
pacman::p_load("ggstatsplot")


AUC_folds_summary_plot <- tibble(label = AUC_folds_summary$label, 
                                 AUC = AUC_folds_summary$mean)

a = tibble(x = factor(AUC_folds_summary$label,  levels = c(  "PPI only" , "all networks"  , "significant networks")), y = AUC_folds_summary$mean)

ggwithinstats(data = a,
              x = x,
                    y = y,
                      type = "np") + xlab("AUC")


```



# relationship between the disease, number of signifiant networks, and number of genes

```{r}
## load the LCC results 

result_folder<-"../cache/output/Orphageneset_rare/"
result_df<-readRDS(paste0(result_folder, "LCC_and_distance_calculation_results.RDS"))

source("../functions/process_LCC_result.R")
result_df<-process_LCC_result(result_df, network_annotate=F)

## count number of networks, only coex

n_signif_df<-result_df %>% dplyr::filter(LCC.signif != "none", grepl("coex", network)) %>% group_by(name)  %>% count(name)

## load the gene sets
source("../functions/readdata_functions.R")
Orphanet_df<-process_disease_genes_data("../data/table_disease_gene_assoc_orphanet_genetic.tsv", min_gene=20, max_gene=2000)
Orphanet_n_gene_df<-Orphanet_df$disgene_df
```

# Relative performance between all networks and selected networks

```{r}
AUC_folds_perf_compare <- AUC_folds_summary %>% 
  dplyr::select(-Q25, -Q75) %>%
  spread(., label, med) %>%
  mutate(dif = `significant networks` - `all networks`) %>%
  left_join(x=., y = n_signif_df) %>%
  left_join(x=., y = Orphanet_n_gene_df[,c("name","N")])

p <- ggplot(AUC_folds_perf_compare %>% mutate(label = ifelse(dif< 0, name,"")), aes(x = n, y = dif)) + geom_point(aes( size = N), col = "grey40") + theme_minimal() + guides(size = F) + geom_hline(yintercept = 0, linetype = "dotted", col = "grey20") + xlab("# significant tissues") + ylab("Performance Difference") 

ggsave("../Figs/scatter_AUC_difference_signif_minus_allnets_vs_ntissues.pdf", height = 3, width = 2.5)

p
```

# Absolute performance

```{r}
AUC_allnets_median <- AUC_folds_summary %>% 
  dplyr::select(-Q25, -Q75) %>%
  dplyr::filter(label == 'significant networks') %>%
  left_join(x=., y = n_signif_df) %>%
  left_join(x=., y = Orphanet_n_gene_df[,c("name","N")])

p <- ggplot(AUC_allnets_median, aes(x = N, y = med)) + geom_point(aes( size = N), col = "grey40") + theme_minimal() + guides(size = F) + xlab("# associated genes") + ylab("median AUC") + scale_x_log10()

ggsave("../Figs/scatter_AUC_signif_vs_Ngenes.pdf", height = 3, width = 2.5)

p
```


```{r}

names(short_names) <- AUC_folds_perf_compare$name

p <- AUC_folds_perf_compare %>%
  ungroup %>% 
  mutate(name = fct_reorder(name, n),
         name_short = factor(name, levels = levels(name), 
                             labels = short_names[levels(name)])) %>%
  ggplot(., aes(x = name_short, y = n, fill=dif)) + geom_col() + theme_minimal() + coord_flip() + scale_fill_gradient2() + ylab("# Significant tissues") + xlab("") + labs(fill = "")+ ggtitle("Performance difference", subtitle = "Selected networks vs all networks")

ggsave("../Figs/barchart_n_tissues_vs_performance_difference.pdf", height = 4, width = 6)

p
```


```{r}
# combine all the stats

disease_stats_df<-inner_join(AUC_folds %>% group_by(name) %>% summarise(medianAUC=median(AUC)), Orphanet_n_gene_df %>% select(name, N)) 

disease_stats_df<-inner_join(disease_stats_df, n_signif_df)

disease_stats_df<-disease_stats_df %>% rename(ngene=N, n_signif_net=n)

p1<-ggplot(disease_stats_df, aes(x=ngene, y=medianAUC)) + geom_point() + scale_x_log10() + xlab("number of genes in the disease set") + ylab("median AUC")
p2<-ggplot(disease_stats_df, aes(x=n_signif_net, y=medianAUC)) + geom_point() + xlab("number of significant networks") + ylab("median AUC")
p3<-ggplot(disease_stats_df, aes(y=n_signif_net, x=ngene)) + geom_point() + ylab("number of significant networks") +  xlab("number of genes in the disease set") + scale_x_log10()

p3 + p1 + p2
```


