---
title: "LCC randomisation comparison"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
fig.path = "../Figs/LCC_randomisation_analysis/"
knitr::opts_chunk$set(echo = FALSE)#, fig.path=fig.path)
```

```{r}
# load  network labels
network_info = read_tsv("../data/network_details.tsv")


# load ranodmization (LCC results)
lcc_stat_vals  = readRDS("../cache/LCC_stat_compute_vals_all_networks.RDS")
lcc_stat_vals_full_df = bind_rows(lcc_stat_vals, .id = "network")
lcc_stat_vals_full_df = left_join(lcc_stat_vals_full_df, network_info)

example_nets = c("co-essential", "ppi", "HP", "GOBP", "reactome_copathway", "coex_ADS")

lcc_stat_vals_df  = lcc_stat_vals_full_df %>% dplyr::filter(network %in% example_nets)
```



```{r LCC_size_vs_node_size}
p <- ggplot(lcc_stat_vals_df %>% 
              dplyr::filter(type == "predicted") %>%
              mutate(network = factor(network, levels = network_info$network, labels = network_info$subtype))
            , aes(x = N_node)) + xlab("Number of nodes") + scale_x_log10()

p <- p   + geom_ribbon(aes(ymin = mean-sd, ymax = mean+sd), fill = "grey70") + geom_line(aes(y = mean)) + scale_y_log10()  + ylab("Largest component size") + facet_wrap(.~ network, ncol = 3) + theme_minimal()

ggsave(paste0(fig.path, "LCC_size_vs_node_size.pdf"), p, width = 4, height = 5)

p
```


# Add the LCC results for the rare genetic diseases

```{r}
source("../functions/process_LCC_result.R")
result_df =  readRDS("../cache/output/Orphageneset_rare/LCC_and_distance_calculation_results.RDS")
result_df_orig = process_LCC_result(result_df)

# take mean and sd from the precomputed version
result_df_precompute = left_join(result_df, lcc_stat_vals_full_df %>% dplyr::filter(type == "predicted") %>% select(-type), by = c("network", "N_in_graph" = "N_node")) %>% mutate(LCC.mean = mean, LCC.sd = sd, LCC.zscore = (LCC.size - LCC.mean)/LCC.sd) %>% select(1:8)

# process the precomputed result
result_df_precompute_processed = process_LCC_result(result_df_precompute)

# merge the exact and precomputed, by common variables (check if all entries are the same)
common_var = sapply(colnames(result_df_precompute_processed), function(x) all(result_df_precompute_processed[,x] == result_df_orig[,x], na.rm = T))

result_df_combn = inner_join(result_df_orig, result_df_precompute_processed, by = names(common_var)[common_var])
```


```{r LCC_size_vs_node_sizewith_signif}

# select subsets of networks to plot
result_selected_df = result_df_orig %>% 
  mutate(N_node = N_in_graph, mean = LCC.size, sd = NA, type = "diseaseval") %>% 
  select(colnames(lcc_stat_vals_df)) %>%
  dplyr::filter(network %in% example_nets)

# modify the data to plot
plot_data = bind_rows(lcc_stat_vals_df, result_selected_df)

plot_data = plot_data %>% mutate(network = factor(network, levels = network_info$network, labels = network_info$subtype))

p <- ggplot(plot_data %>%  dplyr::filter(type == "predicted"),  
            aes(x = N_node)) + xlab("Number of nodes") + scale_x_log10()

# plot <-  p   + 
#   geom_ribbon(data = subset(plot_data,type == "predicted"), aes(ymin = mean-sd, ymax = mean+sd), fill = "grey70") + 
# geom_line(data = subset(plot_data,type == "predicted")  ,aes(y = mean)) +
#   geom_point(data = subset(plot_data, type == "diseaseval"), aes(y = mean), fill = "grey40") +
#   scale_y_log10()  + ylab("Largest component size") + facet_wrap(.~ network, ncol = 3) + theme_minimal()


plot <-  p   + 
  geom_ribbon(aes(ymin = mean-sd, ymax = mean+sd), fill = "grey70") + 
geom_line(aes(y = mean)) +
  geom_ribbon(aes(ymin = qnorm(0.95)*sd+mean, ymax = Inf), fill = "#e5f5f9", alpha = 0.5) + 
  geom_line(aes(y = qnorm(0.95)*sd+mean), col = "#2ca25f", linetype = 2) +
  geom_point(data = subset(plot_data, type == "diseaseval"), aes(x = N_node, y = mean)) +
  scale_y_log10()  + ylab("Largest component size") + facet_wrap(.~ network, ncol = 3) + theme_minimal()


ggsave(paste0(fig.path, "LCC_size_vs_node_size.pdf"), plot, width = 6, height = 4)

plot
```



```{r zscore_precompute_comparison}
p = ggplot(result_df_combn) + geom_point(aes(x = LCC.zscore.x, y = LCC.zscore.y)) + geom_abline(slope =1, intercept = 0, col = "red") +
  xlab("z-score (exact)") + ylab("z-score (precomputed, interpolated)") + 
  ggtitle("Comparison of module significance: exact vs sampling & interpolation") + theme_minimal()

ggsave(paste0(fig.path, "zscore_precompute_comparison.pdf"), p, width = 4, height = 4)

p
```

##
```{r}
network_signif_folds_df = bind_rows(network_signif_all_folds)

ggplot(network_signif_folds_df %>% dplyr::filter(name == disease_current))+ geom_tile(aes(x = network, y = iter, fill = LCC.signif))
```


