---
title: "Grouping of rare diseases and percolation"
output: html_notebook
---

This is to address the problem of sscarcity of rare disease genes association if looking at the annotation of disease genes to its immediate 

```{r setup: include = FALSE}
orpha_gene_onset_df = readRDS("../cache/orpha_gene_onset_df.RDS")

source("../functions/readdata_functions.R")
gene_disease_orpha = process_disease_genes_data("../data/table_disease_gene_assoc_orphanet_genetic.tsv", 1, 2000)


#source("../source/read_orphanet_gene_association_data.R")

gene_disease_orpha = gene_disease_orpha$disgene_df
```


```{r}
# from orphanet_mapping_top_branch

gene_per_disease = orpha_gene_onset_df %>% 
  dplyr::filter(!is.na(gene)) %>% 
  count(orphaID)

gene_per_disease_count = gene_per_disease %>% 
  mutate(group = cut(n, breaks = c(0:10, 100), labels = c(1:10, "> 10"))) %>% 
  count(group)

ggplot(gene_per_disease_count, aes(x = group, y =n)) + geom_col() +
  ggtitle("Most orphanet diseases are immediately associated with one gene") +
  theme_minimal() + ylab("Number of diseases") + xlab("Number of genes per disease")#+ scale_y_log10()
```

Taking the ontology structures into account 

```{r}
#gene_per_disease_group = gene_disease_orpha %>% 
 # mutate(group = cut(n_genes, breaks = c(seq(0,100,20), seq(200,1000, 200), Inf))) %>% count(group)

#ggplot(gene_per_disease_group, aes(x = group, y =n)) + geom_col() +
#  ggtitle("Most orphanet diseases are immediately associated with one gene") +
#  theme_minimal() + ylab("Number of diseases") + xlab("Number of genes per disease")#+ scale_y_log10()

# number shift
gene_per_disease_group = gene_disease_orpha %>% mutate(disease = "OrphaNet Group", n = N) %>% select(disease, n)

gene_per_disease = gene_per_disease %>% mutate(disease = "Orphanet individual")

gene_per_disease_both = bind_rows(gene_per_disease %>% select(disease, n), gene_per_disease_group) %>% dplyr::filter(n>0) 

gene_per_disease_both_count = gene_per_disease_both %>% mutate(group = cut(n, breaks = c(1, 5, 10, 50, 100, 500, 1000, 5000), include.lowest = T)) %>%
  group_by(disease, group) %>% summarise(n = n()) %>% mutate(prop = n/sum(n))

# plot
ggplot(gene_per_disease_both_count, aes(y = prop, x = group)) + geom_col() +  theme_minimal() +facet_grid(disease ~ .) 
```


```{r}

gene_per_disease_both <-gene_per_disease_both %>% mutate(disease = factor(disease, levels = c("Orphanet individual", "OrphaNet Group")))

p <- ggplot(gene_per_disease_both, aes(n)) + geom_density(fill = "grey80") +   theme_minimal() +facet_grid(disease ~ ., scales = "free") + scale_x_log10() + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank()) + xlab("Number of genes per disease") + geom_vline(xintercept = 20, linetype = "dashed", col = "red")

ggsave("../Figs/orphanet_individual_vs_grouped_diseases.pdf", p, width = 3, height = 2)

p
```

## voronoi tree map for ontology representation of rare diseases
```{r}
# download the association
library(RColorBrewer)

orphanet_gene_association <- read_tsv("../data/orphaNet_disease_gene_association_with_roots.tsv")

orphanet_gene_association_unique_root <- orphanet_gene_association %>%
  separate_rows(., roots, sep = ";", convert = T) %>% dplyr::filter(!is.na(roots)) %>% 
  mutate(roots = as.factor(roots))

## take a function to allow modifying alpha values
# Add an alpha value to a colour
add.alpha <- function(col=NULL, alpha=1){
  if(missing(col))
    stop("Please provide a vector of colours.")
  apply(sapply(col, col2rgb)/255, 2, 
                     function(x) 
                       rgb(x[1], x[2], x[3], alpha=alpha))  
}

# define colours for all disease groups
mycolors <- colorRampPalette(brewer.pal(8, "Set2"))(nrow(gene_disease_orpha))

# add id 1-28
gene_disease_orpha$id = 1:nrow(gene_disease_orpha)

# add colour with corresponding alpha values to each disease group
gene_disease_orpha_mod <- gene_disease_orpha %>% 
  rowwise() %>%
  mutate(col =mycolors[id])
  #mutate(col = add.alpha(mycolors[id], N/max(gene_disease_orpha$N)))

gene_disease_orpha_mod$root = "Orphanet"

# load voronoi treemap package
#pacman::p_install_gh("https://github.com/uRosConf/voronoiTreemap")
library(voronoiTreemap)
data(ExampleGDP)

gdp_json <- vt_export_json(vt_input_from_df(ExampleGDP, hierachyVar0 = "h1", hierachyVar1 = "h2", hierachyVar2 = "h3", colorVar = "color", weightVar = "weight", labelVar = "codes"))

vt_d3(gdp_json)
```

```{r}
gene_disease_orpha_mod$plotlab = ""
onto_json <- vt_export_json(vt_input_from_df(gene_disease_orpha_mod, hierachyVar0 = "root", hierachyVar1 = "name", hierachyVar2 = "name", colorVar = "col", weightVar = "N", labelVar = "plotlab"))

vt_d3(onto_json)
```

```{r}
# onto to json version detailed
orphanet_gene_association_unique_root$h0 = "OrphaNet"
orphanet_gene_association_unique_root$col = mycolors[orphanet_gene_association_unique_root$roots]
orphanet_gene_association_unique_root$plotlab = ""

onto_json <- vt_export_json(vt_input_from_df(orphanet_gene_association_unique_root, hierachyVar0 = "h0", hierachyVar1 = "roots", hierachyVar2 = "label", colorVar = "col", weightVar = "n_genes", labelVar = "plotlab"))

vt_d3(onto_json)

```


## Circle packing for demonstrate disease gene association scarcity

```{r}
library(ggraph)
library(igraph)
library(tidyverse)
library(viridis)
 
# We need a data frame giving a hierarchical structure. Let's consider the flare dataset:
edges <- flare$edges
vertices <- flare$vertices
mygraph <- graph_from_data_frame( edges, vertices=vertices )
 

edges <- term_childern_df

# get descendant


mygraph <- graph_from_data_frame( edges)

# select only the LCC
non_lcc_nodes = components(mygraph)$membership
non_lcc_nodes = names(non_lcc_nodes)[non_lcc_nodes != 1]

mygraph <- graph_from_data_frame( edges %>% dplyr::filter(!from %in%non_lcc_nodes, !to %in% non_lcc_nodes))

vertices <- flare$vertices

# Control the size of each circle: (use the size column of the vertices data frame)
p <- ggraph(mygraph, layout = 'circlepack', weight="size") + 
  geom_node_circle(aes(fill = depth)) +
  theme_void() + 
  theme(legend.position="FALSE")
p


```

